//Horoszkóp lista
const horoscopes = {
    kos: [
        "Visszafordíthatatlan átalakulást jelez a Plútó bolygó, mely végleg kilép a Bakból november 19-én éjjel. Előtte még van lehetőséged azokat a gyökeres változtatásokat véghez vinni, vagy legalább elkezdeni, amelyek a körmödre égnek. De ezt semmiképp se november 3-ra időzítsd, mert a Mars-Plútó szembenállás kíméletlen veszekedést jósol. Szerencsére Vénusz, a Kis szerencse bolygója november 11-én belép a Bakba, és kis szerencsét hoz magával. Ez arra jó, hogy optimistábban lásd a jelent és a jövőt is.",
        "Bolygód, a Szaturnusz november 4-én több mint 4 hónap hátrálás után végre elindul előre. Ettől visszanyered a jövőbe és az életbe vetett hitedet. Emellett ha jót akarsz magadnak, akkor minden beszélgetésbe kapcsolódj be, mert fontos információkhoz juthatsz. Tanulás és/vagy utazás lehetőségét is mutatják a bolygók. Kár lenne kihagynod. Szinte biztos, hogy megbánod, ha nem mész. Nagy kihívás lesz számodra, hogy gyerekes szócsatákból kimaradj 3-án, 4-én, 11-én és 13-án.",
        "Ha jót akarsz magadnak, akkor novemberben minden beszélgetésbe kapcsolódj be, mert fontos információkhoz juthatsz. Emellett tanulás és/vagy utazás lehetőségét is mutatják a bolygók. Kár lenne kihagynod. Szinte biztos, hogy megbánod, ha nem mész. Ezzel párhuzamosan a bevételeid nem úgy alakulnak, ahogy szeretnéd. És nem vigasztal, hogy most mindenkinek nehéz. Kritikus napok: november 7., 10., 11. Ezeken a napokon borúsabban látod a helyzetedet.",
        "A kapcsolódás, kapcsolatteremtés válik hangsúlyossá minden vonalon. Itt az ideje, hogy tisztázd az érzéseid, és megnyugvást találj másokkal való kapcsolataidban. Személyes kötelékeid is megerősödnek. Ha szingli vagy, most rád köszönhet a szerelem, ha kapcsolatban élsz, ismét átélhetitek a régi szenvedélyt. Szakmai téren is a csapatmunka a gyümölcsöző. A Mars és a Merkúr is hangsúlyossá teszi a kapcsolatteremtést, mind társasági, mind szakmai értelemben.",
        "Ebben a hónapban karrierjében sikert-sikerre halmoz, ezt az Újhold segíti elő! Az eddigi szorgalmas munkájának gyümölcsét most aratja le, a Jupiter-Plútó együttállása is erre utal. az első sorsterületen halad a Szaturnusz is, ami ad még némi feladatot, amit a Bak szó nélkül teljesít, annyira szomjazik a sikerre. Szerelmi-téren nem igazán tudja még elhatározni magát: vagy a partner nem alkalmas a tartós kapcsolatra a megítélése szerint, vagy a saját vagyonát tartja kevésnek a családalapításhoz.",
        "A munkahelyén mostanában kissé leterhelte magát, ez gyengélkedéshez vezet, nincs olyan jó állapotban fizikailag, mint szellemileg. A mentális képességei felülmúlhatatlanok, egy nagyobb csoportot érintő találmányával rengeteg összeggel növelheti bankszámláját. Több embert belevon munkájába, de a főszerep az öné. A pénz azonnal áramlik, de pillanatnyilag meg sem közelíti a későbbi eredményeket. A szerelem lehetősége is megnő. Bár ön nem könnyű természet, jót tenne magának is, ha jobban kimutatná az érzelmeit.",
        "Ez a hónap eléggé nehéznek látszik, sok erőt és kitartást követel öntől, de szerencsére ezt megadja a Szaturnusz és a Plútó is a Bak jegyében. A Jupiter jegyet vált, és a Nyilas jegyében folytatja útját. Muszáj lesz saját magát lelkesítenie. Bízzon önmagában, hiszen ön mindent meg tud csinálni! November 15-től a Mars is jegyet vált, átlép a Halak jegyébe, ez pedig erősíteni fogja önt.",
        "Semmi sem akadályozza meg, hogy egyre feljebb és feljebb kerüljön azon a bizonyos szamárlétrán. Az igazság az, hogy a jó sorsfordulathoz most még a nehézségek is hozzásegítik. Vagy azért, mert tanul belőlük, és e tudásából másoknak is juttat, vagy azért, mert éppen ezek inspirálják a további útkeresésre.",
        "Mint mindig, most is a legjobb, ha a hivatását helyezi előtérbe. Nagy lépésekkel tud most előrehaladni, és ezt a felettesei is értékeli fogják. A Merkúr a hónap első felében szenzációs üzleteket ígér, és mire jegyet vált, addigra a Vénusz már a Bak jegyébe lép. Ez nem csak a szerelmi életét javítja, hanem az anyagi ügyeit is. Az egyik legjobb hónapja lesz ez, akár egyedülálló, akár párban él!",
        "Az Ön jegyében áll a Plútó, de kellemetlen kapcsolatban van az Uránusszal. Akár érzékeli a változásokat már az életében, akár nem, a környezete másképp kezd el Önhöz viszonyulni, és ez mindenképp válaszlépésekre, változásokra kényszeríti majd Önt. Ne próbáljon szemet hunyni efelett, különben még kellemetlenebb formában lesz kénytelen szembesülni a tényekkel. Nézzen szembe önmagával és belső változásaival, így erősebb és nemesebb emberként kerülhet ki ebből a tranzitból."
    ],
    bika: [
        "A Vénusz együtt áll a Marssal a Szűz jegyében, és itt tartózkodik a Jupiter is, a nagy szerencse bolygója. Minden jól megy ebben a hónapban az életében. A karrierje is és a szerelmi élete is jól alakul. Bármilyen ügyben a legjobb eredményeket tudja elérni. Ha hivatásában tervezi a változást, esetleg egy másik helyre szeretne menni dolgozni, akkor már el is kezdheti ennek megvalósítását. Most kérjen fizetésemelést, mert meg is kaphatja. Ha új vállalkozást szeretne indítani, az is sikerülni fog.",
        "A szerelem bolygója a Vénusz, a hónap első két hetében még a Nyilas jegyében áll, pontosan szemben az Ön jegyével. Ha Önnek van párja, akkor ez a szenvedélyt csak fokozza majd. Ha Ön egyedülálló, akkor biztos lehet benne, hogy a jövendőbelije nagyon közel van Önhöz… Lehetséges, hogy már ismerik egymást. A Merkúr a hónap második felében új megbízásokat és kitűnő kapcsolatokat szerezhet önnek.",
        "A hónap 7. napjától a Vénusz szembenállásba lép az ön jegyével, ez nagyon szenvedélyessé teszi. Ha ön szingli, akkor megismerkedhet valakivel, és bár nincs meggyőződve róla, hogy az illető lenne az igaz, mégis elemi erővel vonzza önt a másik… A hivatásában kevesebb lesz az izgalom: a Merkúr és a Mars helyzete miatt most ne számítson gyors sikerekre, kitartóan és keményen kell dolgoznia.",
        "A Merkúr kedvezőtlen fényszögben áll a Bika jegyéhez képest, és november 17-től hátráló mozgásba kezd. Ez nem előnyös helyzet az ön számára, jobb ilyenkor a háttérben maradni. A Vénusz is kedvezőtlen helyzetben áll. Ám a Plútó sok segítséget tud önnek adni a Bak jegyéből. Öröklött képességeivel most sokra mehet! Egy kiadós baráti beszélgetés is sokat segíthet abban, hogy visszatérjen az életkedve. Találhat magának egy új hobbit, amiben végre örömét leli.",
        "Az egész hónapot az határozza meg, hogy párkapcsolatát végre rendezni tudja, lehet, hogy csak átmenetileg, de ez önnek több szempontból is fontos. Egyrészt szereti ezt az embert, másrészt, ha önök házasok, akkor azért sem gondol a szakításra, mert ön egy házasságot felbonthatatlan egyezménynek tart. A hónap végén még akadnak nézeteltérések, meglátjuk, hogy mennyire van türelme... A munkahelyén viszont nagyon meg vannak önnel elégedve. Még egy tanulmányútra is elküldenék.",
        "A Merkúr a hónap első napjaiban még hátrál, és igen kellemetlen fényszögeket kap, tehát a szerződéseket, banki hitelek feltételeit részletesen és alaposan beszélje át! A hónap közepén lesz egy Skorpió-újhold, az zöld lámpát ad a terveinek. Addig próbáljon meg nem idegeskedni, nem feszülni, kellemes hangnemet megütni ismerőseivel, főleg azzal a személlyel, aki az ügyeit kezeli. A kilencedik sorsterületéről nagyon sok segítséget kap a Jupiter-Plútó együttállástól: bizony nem lehetetlen, hogy ön még az idén új ingatlan tulajdonosa lesz.",
        "A tárgyalások kiemelten szerepelnek ebben az időszakban az életedben. Kedvező időszak új kapcsolatokra vagy a meglévők újrafogalmazására. Előtérbe kerülnek a megosztás és a partnerség kérdései, ez az Újhold hatása. Ezzel a pozícióval gyakran összefüggésbe hozható annak az érzése, hogy valakire jó támaszkodni. Jelenleg jó ötlet a kölcsönösen támogató kapcsolatokon dolgozni, mert a Mars és a Merkúr is támogatja a közös érdekeket. Lehet, hogy rájössz, hogyan élheted meg harmonikusan természeted gyengéd oldalát, ezt még a Bikában kialakuló Telihold is aláhúzza. Ezenkívül jó alkalom a kapcsolatteremtésre és annak nyilvánosságra hozatalára, melyet a Vénusz elősegít.",
        "November komoly nyomokat hagy benned. Felkavarhatja az életedet a szerelem. Akkor is, ha van, és akkor is, ha még nincs párod. Előbbi esetben a féltékenységet mindenáron zárd ki! Szakítás veszélyt mutatnak a bolygók 5-én, 8-án, 9-én és 29-én. Ám ha még nincs párod, szabad a pálya. Bár az új szerelem frusztráló lehet 5-én, 8-án, 9-én és 29-én. A másik hangja és beszéd stílusa ezeken a napokon nem lesz kellemes. De nem csak párkapcsolati vonatkozásban…",
        "November lesz az év legrázósabb hónapja a te szempontodból. Vigyázz mindenkire, aki fontos neked, mert szakító próbának lesz kitéve minden kapcsolatod! Kerülj minden vitát! Szakításveszélyt mutatnak a bolygók 3-án, 4-én, 11-én és 13-án. Akkor lehet baj, ha hevesen reagálsz. Hiába van igazad, nem tudod érvényre juttatni, mert a másik a stílusoddal és nem az érveiddel foglalkozik. Bolygód, a Vénusz 8-tól segít, hogy diplomatikusabban fogalmazz…",
        "Valószínűleg nem a november lesz a kedvenc hónapod. Elengedhetetlen, hogy felkészülj azokra a kihívásokra, amelyeket több bolygószembenállás szimbolizál. Legrázósabb napok: november 15. és 17. Ezeken a napokon mindenáron és minden eszközzel kerülnöd kell az összetűzést. Ezen kívül lesz még két másik bolygószembenállás 3-án és 18-án, amelyek a pénzügyeidet érintik kényelmetlenül. Ha valamilyen nagyobb beruházáson gondolkozol, a döntést ne erre a két napra időzítsd!"
    ],
    ikrek: [
        "Bolygód, a Merkúr november 2-án jegyet vált, és azonnal uralmi cserébe kerül az Ikrekben járó Jupiterrel. Ez momentán nem jó hír. Több vetülete is van ugyanis ennek: 1. Beszéded szenvedélyessé, de érthetetlenné válik mások számára. 2. Túl sokat adsz mások véleményére. 3. Érteni akarod, a másik miért tesz vagy mond bizonyos dolgokat. Könnyen lehet, mind a három hozzáállás zsákutca, különösen november 18-án, amikor a Merkúr és a Jupiter ráadásul még szembe is kerül egymással…",
        "Nem leszel topon november első napjaiban. Bolygód, a Merkúr meghűlést és/vagy gyengélkedést mutat. Előzd meg a nagyobb bajt sok mézes teával, gyömbérrel, citrommal és fokhagymával! Közben nem szabad panaszkodnod se az időjárásra, se a munkádra, mert ezek is lebetegíthetnek. A kimondott szónak teremtő ereje van. 10-től Merkúr a Nyilasban ellentmondásos találkozásokat jelez. Számíts rá, hogy lesz, amelyik vonz, és lesz, amelyik taszít!",
        "A retrográd Mars az egész novembered belengi. Most nem szabad semmit és senkit sürgetned. Önmagadat sem. Emellett aggodalom tölthet el az egészséged megtartása miatt. A hűvös idő jogossá teszi ezt. Muszáj mindig rétegesen öltöznöd, és csupa olyan élelmiszert fogyasztanod, ami vitaminokkal és ásványi anyagokkal tölti fel a szervezetedet. 16-án Vénusz, 17-én Merkúr, 22-én Nap vált jegyet, és a szerelmi életed felpörög…",
        "Az Újhold hatására most sikeresen meg tudod reformálni azt, amiről úgy érzed, igényli a változtatást: legyen szó új étrendről, szokásokról, munkaredről, most bármelyik területet megújíthatod. Ez az üzleti ügyek intézésének, a részletek kezelésének és a hatékonyság növelésének ideje, amiben a Mars és a Merkúr is segítségedre lehet. Jó alkalom ez mindenféle elemzésre is, mivel a kritikai gondolkodásod most a csúcsán van. Ezt az időszakot a dolgok rendezésének vágya jellemzi, de a hasznosság is fontos, ebben a Vénusz sokat segít neked.",
        "A hónap elején a Merkúr kedvezőtlen helyzete keresztülhúzhatja a számításait. Ne türelmetlenkedjen, mert a sors kárpótolja mindenért, negyedikén a Merkúr, tizedikén pedig a Mars elindul előre, és semmi nem tudja megállítani a sikerszériáját! A Jupiter-Plútó együttállás végre megengedi, hogy a majd egy éve önhöz közeledő óriási összeg most tisztázottan meg is érkezzen. A Skorpió-újhold megváltozott munkakörülményeket hoz, minden az elvárásai szerint alakul.",
        "Hivatalában nem mindennapi lehetőséget kap, még az is lehet, hogy külföldön folytathatja tovább a munkáját. Ön most tele van kalandvággyal, ezért nagyon örülne neki. Aggódik, hogy vajon megkapja ezt a lehetőséget. Szinte biztos lehet benne, a hatodik sorsterületén a Vénusz és a Jupiter együttállásban van a Nyilas jegyében, amely szintén a külföldöt is jelentheti. Ha teheti, csak november 20-a után vállalja el ezt az állást.",
        "A Vénusz a Mérleg jegyében áll: ez biztosítja a tiszta kapcsolat boldogságát. Egy zavaró tényező mégis lehetséges, ha találkozókkal zsúfolja tele a napjait, ahelyett, hogy a kedvesével lenne. Kaphat egy érdekes telefonhívást, ennek hatására teljesen más szemmel fogja látni a pénzügyi helyzetét. November közepétől érdemes jobban figyelni az egészségére. A Mars jegyet vált, a Halak jegyében folytatja útját, arra figyelmezteti önt, hogy többet kellene pihennie, aludnia.",
        "A hónap első napjai fárasztónak ígérkeznek, a második héttől kiemelkedő sikerekre számíthat a munkahelyén. A Merkúr szembenállása miatt jó ajánlatot kaphat, ezt alaposan meg kellene fontolnia. Az emberi kapcsolatok terén viszont sok feszültség várható.",
        "A szerelem bolygója a Vénusz, a hónap első két hetében még a Nyilas jegyében áll, pontosan szemben az Ön jegyével. Ha Önnek van párja, akkor ez a szenvedélyt csak fokozza majd. Ha Ön egyedülálló, akkor biztos lehet benne, hogy a jövendőbelije nagyon közel van Önhöz… Lehetséges, hogy már ismerik egymást. A Merkúr a hónap második felében új megbízásokat és kitűnő kapcsolatokat szerezhet Önnek.",
        "A Vénusz, a Mars és a Merkúr is jegyet fog váltani ebben a hónapban. November 8-án a Vénusz már a Mérleg jegyébe fog lépni, ez pontosan az Ön szerelmi házát érinti. Ha Ön egyedülálló, ekkorra találhat párt magának, ha már párkapcsolatban él, akkor a jelenlegi kapcsolatát tudja rendbe hozni. Szuper időszak ígérkezik arra, hogy örömét találja a szép dolgokban, és a környezetét csinosítsa. Jól fogja érezni magát, sőt hajlamos lesz arra is, hogy túl sokat engedjen meg magának. Legyen minél többet szerettei körében."
    ],
    rák: [
        "A Merkúr november 2-án a Skorpió jegyébe lép, és a lehető legjobb fényszögben lesz az ön jegyével. Remek alkalmak nyílnak kapcsolatainak a javítására, különösen a nőkkel, mivel érzelmileg azonos hullámhosszra kerül velük. De ebben az időszakban egyébként is mindenki szívesen szóba elegyedik Önnel és értékelni fogja őszinteségét. Új üzleti lehetőségeket kap, és még utazhat is akár. Karrierje építése közben ne feledkezzen meg a szerelemről sem!",
        "A hónap második felében a Vénusz már a Bak jegyében fog járni, és szemben fog állni az Ön jegyével. Ez igazi szerelmet ígér! A Bak jegyében álló Vénusz még azt is lehetővé teszi, hogy egy régi partnerével újra kezdhesse a kapcsolatot, természetesen csak ha ezt szeretné. A hivatásában a Merkúr csak az első két hétben tudja segíteni, így erre kellene a hangsúlyt helyeznie. Most biztos lehet abban, hogy sikerül több pénzt keresnie. Összességében nagyon jó hónapnak ígérkezik a november.",
        "A Mars pozíciója töprengésre készteti, és hajlamos lehet minden feladatot halogatni. A szerencséjét azonban ezzel sem tudja elrontani, most mintha megvárnák a lehetőségek, amíg döntésre jut – ez a Jupiter helyzetének köszönhető. A hónap közepe táján sorsszerű találkozásban lehet része.",
        "Fontos, hogy meggondoltabb váljon. A Jupiter november 8-án átlép a Nyilas jegyébe, és a Vénusz sem áll túl kedvezően. Ha már elromlott a párkapcsolata, azt nagyon nehéz lesz helyrehozni. Hatalmi harcokat kell vívnia, sőt a szakítás lehetősége is ott lebeg a levegőben. Hivatásában sem mennek simán a dolgok, több gátló tényező is akadályozhatja. Most ne hozzon fontos döntéseket, és maradjon következetes. Immunrendszerét muszáj lenne erősíteni, vásároljon vitaminokat.",
        "A hónap első napjaiban önre köszönthet egy munkahelyi szerelem, vagy egy régi kedvese térhet vissza önhöz. Mindenesetre bővül a család. Az egészségi állapota kiváló állapotban, van. Ha a munkája a szépségiparhoz, vagy művészethez kapcsolódik, akkor most ön nagyon sokat dolgozik és reméljük, hamarosan ki is fizetik, pénzügyekben számíthat egy kis csúszásra.",
        "Az Újhold az önkifejezést teszi lehetővé, és a Mars és a Merkúr is felkapcsolja a kreativitásod. A romantikus hajlamokat is kiemelik, csakúgy, mint mindenféle szórakoztató játékot és csak a gondtalan, örömteli hangulatot. Remekül szót értesz mindenkivel, és meg tudod szerezni mások támogatását, ha arra van szükséged. Ez egy szenvedélyes időszak lehet számodra, a szokásosnál merészebbnek érezheted magad. Ragyogni fogsz, és sok hódolót szerzel!",
        "Jó hír, hogy novemberben elemedben leszel! Számtalan ötlet pattan ki a fejedből. Azonban a Szaturnusz azt javasolja, hogy kapkodás helyett készíts tervet! Az első lépés, hogy írd le mindazt, ami fellelkesít! Utána jöhet a prioritás felállítása. Ezzel párhuzamosan sajnos egy barátság nehéz időszakon megy keresztül. Vagy el fogtok távolodni egymástól, vagy ellentétes véleményen lesztek. Legkritikusabb napok: november 5., 8., 9. és 29.",
        "Végre novemberben elemedben leszel. Millió ötlet pattan ki a fejedből. Szaturnusz is segít (november 4-től előre mozog), és azt javasolja, hogy kapkodás helyett készíts tervet! Először szedd össze, hogy pontosan mi minden lelkesít! Utána jöhet a prioritás felállítása. Ezzel párhuzamosan sajnos egy barátság nehéz időszakon megy keresztül. Vagy el fogtok távolodni egymástól, vagy ellentétes véleményen lesztek. Legkritikusabb napok: 3, 4, 11 és 13.",
        "Itt az ideje tudomásul venni és értékelni, hogy milyen szerencsés vagy. Az egész novembert átlengi egy szerencsés bolygóháromszög, amely nemcsak szerencsét, hanem védelmet is szimbolizál. Szükséged lesz a szerencsére és a védelemre, mert egy november 3-i Mars-Plútó szembenállás viszály veszélyét jelzi. Ha ezt megúszod sértődés és szakítás nélkül, akkor megveregetheted a válladat, mert valamit végre megtanultál és jól csináltál. Ez nem a konfliktus kerülése, inkább a konfliktus kezelése…",
        "A hónap első napjaiban jobb, ha el sem megy üzleti találkozóira, nincs a jegy szülöttére jó hatással a Merkúr-Szaturnusz kvadrátja, késlelteti az üzleti ügyeit, és egészségügyileg sincs a legjobb állapotban. A Skorpió-újhold a hónap közepén nagy örömben részesíti, ez leginkább szerelmével vagy gyermekével lehet kapcsolatban: összeköltözés, eljegyzés, bármi terítéken lehet..."
    ],
    oroszlán: [
        "A Mars, az energia bolygója az ön anyagiakat jelző területe felett vonul át. Értékei és vagyoni helyzetének kérdései foglalkoztatják majd elsősorban, de lehetőség szerint ne azonosuljon ezekkel a problémákkal. Tegyen meg mindent, amit megtehet, a megélhetéséért, de ne vitatkozzon pénzügyekről másokkal. A Mars még arra is lehetőséget ad Önnek, hogy vagyonát gyarapítsa. Igyekezzen óvakodni a túl nagyvonalú pénzkiadástól.",
        "A Merkúr a hónap elején nem tud Önnek segíteni. A hivatásában semmi sem megy gyorsan, könnyen. A legjobb, amit tehet, ha nagyon óvatos lesz, és inkább csak megfigyelőként vesz részt a dolgokban. A szerelmi élete viszont csodálatosnak ígérkezik. Használja ki, amíg a Vénusz a Nyilas jegyében áll, mert a következő időszak érzelmileg sajnos kevésbé mutatkozik jónak.",
        "A Szaturnusz helyzete erős, emiatt több próbatételre is számíthat. Ezek egyike a kapcsolatait érinti. Ami a hivatását illeti, egyre jobbak lesznek a sikeres működés esélyei. Hallgasson kollégái tanácsaira!",
        "A Vénusz nagyon sokáig áll a Mérleg jegyében, bármilyen őszies is az időjárás, az ön szívében tavasz lesz. Ha ön még egyedülálló, találkozhat valakivel: ebből a kapcsolatból akár még eljegyzés is lehet. Fortuna is önre mosolyog, a hivatásában kiváló kilátásai vannak, ebben a Merkúr és a Jupiter segítik.",
        "A hónap elején még lesz oka némi panaszra az egészségét illetően, de ez nem tart tovább egy hétnél. Lehet, hogy ingatlanvásárlásra adja a fejét, vagy a család többi tagja, és már ki is nézték az ingatlant. Ha ez így van, és önnek is tetszik a lakás, menjen többször el a helyszínre és ne döntsön rögtön, a Merkúr hátráló, most valami nem sikerülne jól. Inkább beszéljenek a részletekről, fizetési ütemezésről, ki mit vállal érte. A szerződéskötés ráér a következő hónapban is.",
        "A munkájában nagy sikerek várhatók, ezt a hatodik sorsterületen együttálló Jupiter-Plútó garantálja, végre eléri a céljait. Minden esemény a hónap közepére várható, főleg hogy a Mars is elindul előre, és végre a Merkúr is. A Skorpió-újhold kedvező hatása valamilyen ingatlan-ügyet segít elő, elképzelhető a költözés is. Úgy tűnik, most fenekestül fordul fel az élete, de a végeredmény igazán boldoggá teszi. Egész évben ezen dolgozott, és a karrier életterületén az Uránusz is a változást fogja elősegíteni.",
        "Az otthon és a család áll most a középpontban. Személyes fejlődési szinten itt az ideje a belső biztonságérzeted felfedezésének, ebben segítségedre lesz az Újhold. Felismered az érzelmi szükségleteidet, és jól is kommunikálod azokat, remek hatások érnek a párkapcsolat, házasság területén. Képes vagy bizalomteljesen kapcsolódni másokhoz, és ha volt/van problémád az intimitással, sebezhetőséggel, most az is feldolgozásra kerül.",
        "November nem indul valami fényesen. Úgy érzed, hogy folyamatosan visszahúznak családi és/vagy ingatlan ügyek. Ez olykor kihoz a sodrodból. Különösen november 5-én, 8-án, 9-én és 29-én. Ezzel párhuzamosan a párkapcsolatod vagy hullámvölgybe kerül, vagy megerősödik. Kettőtökön múlik, hogy mi lesz. Mindez november 16-tól fokozatosan javul. Szóval nincs világvége. Ennek tudata sokat segíthet átvészelni a nehéz napokat.",
        "Az otthon békéjének megóvása a legnagyobb kihívás a számodra novemberben. A családból valaki olykor kihoz a sodrodból. Különösen november 3-án, 4-én, 11-én és 13-án. A legjobb ellenszer, ha semmit sem veszel személyed elleni támadásnak. Feltételezd, vagy bátran kérdezd meg, hogy a másik segíteni akar-e! Fokozatosan javul a helyzet, ahogy bolygók sorban belépnek a Nyilasba: 10-én Merkúr, 22-én Nap, 24-én Mars. Ettől egyre derűsebben látsz mindent.",
        "A november legnagyobb kérdése, hogy mit kezdesz azzal a mérhetetlen energiával, amit az Oroszlánba lépő Mars hoz neked november 4-től? Tovább emeli a vitalitásodat, hogy a Merkúr november 2-án, a Nap pedig 21-én tüzes jegybe lép. Ez mind kedvező. Ellenben a november 19-i Plútó jegyváltásával… Tavaly március 23. óta időszakosan szembesülsz azzal a dilemmával, hogy kit kövess, kivel tervezz hosszú távon. Lassan választanod kell. Ez persze nem jelent sem sürgetést, sem kapkodást…"
    ],
    szűz: [
        "Novemberben hol a múlton rágódsz, hol a jövő miatt aggódsz az égi folyamatok szerint. Tuti, hogy mindkettőt felfokozott módon teszed, köszönhetően bolygódnak, a Merkúrnak, amely 2-án belép a túlzásokra hajlamosító Nyilasba. A másik szélsőség ebben a hónapban, hogy hol begubóznál, hol csomagolnál és azonnal elutaznál. Döntésre alkalmatlan napok: 3., 15., 17. és 18. Ezeken a napokon ne erőltesd a döntést, a legjobb persze, ha a hónap végéig vársz. Tudd, nem maradsz le semmiről!",
        "Igencsak eseménydúsnak ígérkezik a novembered, amit nem fogsz bánni, mert több témában is átbillensz a holtponton. Amennyiben az utóbbi hetekben, hónapokban nem láttál kellően látványos eredményeket, akkor örülhetsz, mert ennek végre vége. A következő területeken várható változás: pénz, párkapcsolat, ingatlan ügyek. Közben legyél óvatos az utakon! Különösen november 3-án, 4-én, 11-én és 13-án. A hónap második felében váratlan vendég toppanhat be…",
        "Nem lesz időd unatkozni. Ugyanis mozgalmasnak ígérkezik a novembered. Ezt nem fogod bánni, mert több területen végre megtörténik az elmozdulás. Az utóbbi hetekben, hónapokban megrekedtél, és nem láttál eredményeket. Most ennek végre vége. Ettől függetlenül egész hónapban legyél óvatos az utakon! Különösen: november 5-én, 8-án, 9-én és 29-én. A hónap második felében váratlan vendég állíthat be hozzád - és maradni akar. A reakciód őszinte lesz…",
        "Az újhold jelzése szerint új ismereteket szerezhetsz, új tudásra tehetsz szert. Jobban oda tudsz figyelni a másokkal való lelki kapcsolat ápolására, éberséged felerősödik, szinte minden részletre kiterjed a figyelmed a hétköznapok során is. Ezt a Mars és a Merkúr haladása is hangsúlyozza. Ez a hónap jó alkalmat kínál a rövidebb utazásokra. Szerelemben, szórakozásban a Vénusz fogad kegyeibe.",
        "Úgy tűnik, hogy szerelmi élete végre rendeződik, a Jupiter-Plútó együttállása jelzi ezt. Ha az idősebb korosztályhoz tartozik, akkor gyermeke élete kerülhet sínre. A Skorpió-újhold új szokásokat, rövid feladatokat, utazásokat hoz az életébe, amelyek kirángatják a megszokott rutinból. Szépen alakul az élete év végére, a zodiákus legboldogabb embere lehet!",
        "A munkahelyén nagy megbecsültségnek örvend, talán kinevezik, vagy egy tanulmányútra küldik - bármelyik is, önnek mindkettőhöz megvan a tehetsége, lehetősége. Ha most elutazik, nagy lehetőségek várnak önre, nemcsak szakmailag, hanem a szerelemben is. Lehet, hogy az illető külföldi, de lehet, hogy magyar, csak az utazás során szeretnek egymásba. A korkülönbség lehetséges, de ön érett személyiség, és ez nem veszi el a kedvét.",
        "A Szűz jegyének uralkodó bolygója a Nyilas jegyében áll, és kellemetlen fényszögben áll uralmi helyével. Ez sok nehézséget okozhat önnek. Talán ez lesz az egyik legrosszabb hónapja... Szakítson időt arra, hogy kicsit visszahúzódhasson, és egyedül legyen, így találhatja most meg a lelki békéjét. Csak ez számítson. Felejtsen el minden mást!",
        "A magánéletében minden kerek. Testileg viszont eléggé kimeríti magát, és ez a munkájára is hatással van. Egyre nehezebben veszi fel a ritmust, és nincs ereje a munkahelyi csatározásokhoz. Vegyen ki pár nap szabadságot!",
        "A Szaturnusz és a Vénusz együtt támadják a Szűz jegyét, legalábbis a hónap elején. A hónap közepe körül javulnak az esélyei, hiszen a Vénusz a Bak jegyébe lép. Akár egyedülálló, akár párban él, mindenképpen jók a szerelmi esélyei. Az Ön uralkodó bolygója, a Merkúr, a hónap elején kedvező munkákat ígér Önnek. Bár ez a hónap elején még nem tűnik így, nagy előrelépést tehet majd a karrierjében. Gyakorolja a bizalom művészetét, és nyugodtan kockáztathat is egy kicsit az üzleti életben.",
        "Az év uralkodó bolygója, a Jupiter most az ön jegyét részesíti a legnagyobb szerencsében. Ön mindig szeretett tanulni, most is ég a tanulási vágytól, keressen a kedvére való tanfolyamok között, és nyugodtan iratkozzon be valamelyikre. Ha még nincs párja, most egy olyan szerelmi kapcsolata kezdődhet, aminek házasság is lehet a vége. A Merkúr a 3. sorsterületen áll. Alkalmat ad Önnek arra, hogy lecserélje autóját egy újra, vagy egy jobb minőségű használtra."
    ],
    mérleg: [
        "Az Uránusz áll Önnel szemben, kellemetlen fényszögben. A szembenállás mindig felveti a párkapcsolati problémákat is. Még egy jónak látszó kapcsolat is kissé göröngyössé válhat ilyenkor, de az, amelyik régóta rejtett problémákkal küszködik vagy közönyös beletörődésbe süppedt, most nagy valószínűséggel véget ér. Lényegében a belső erőviszonyok átrendezéséért és a szabadabb mozgástérért folyik a harc, ha egyik fél sem elég rugalmas a változások elfogadásához, a szakítás szinte elkerülhetetlenné válik.",
        "A Vénusz november első felében még a Nyilas jegyéből mosolyog Önre. Használja ki ezt az időszakot, és közben lassan készüljön fel arra, hogy a hónap második fele sajnos nem lesz ennyire könnyű. Még a legjobb kapcsolat alapja is meginoghat egy picit. A legfontosabb, hogy annyira bízzon a párjában, mint önmagában. Karrierjét kellene építeni a hónap második felétől. A győzelmi sorozat folytatódik.",
        "A Mars az ön jegyében áll, így ez a rendteremtés időszaka lehet. A kapcsolataiban is tisztáznia kell néhány kérdést, elképzelhető, hogy megszakad a kapcsolata néhány emberrel, akik már csak terhet jelentettek önnek. Az életmódváltásnak is kedvez eza a hónap, vágjon bele!",
        "November 16-ig minden úgy történhet, ahogyan ön elképzelte, sikeres lesz a munkahelyén és a szerelemben is. Karrierjében nagy léptékkel haladhat előre, bele kellene adnia minden tudását ebbe. A szerelem is meglehetősen szenvedélyesnek látszik. A Vénusz, a 2018-as év uralkodó bolygója a Mérleg jegyében áll. Sok lehetőséget kap párkapcsolatát megjavítani, harmonikussá tenni.",
        "Óriási összegre tesz szert vagy a munkájából, vagy a szüleitől, de az is elképzelhető, hogy hagyatékkal kell most foglalkoznia. A hatalmas összeget lehet, hogy valamilyen társulásra, vagy befektetésre fordítja, egy dologra kell ügyelni, hogy a hónap végéig ne kössön szerződést. Addig gondolja át, lehet, hogy nem is egy helyre kell önnek ezt az összeget lekötnie, érdeklődjön, részleteket leírhatnak, de a végleges döntése ne szülessen meg ebben a hónapban.",
        "A Vénusz az első sorsterületén oppozíciót alkot a Marssal, ez bizony kétélű kard... Ha önön múlik, akkor kedvességével, kompromisszumkészségével átvészeli ezt az időszakot. Partnere az elmúlt hetekben nagyon sokat küzdött, főleg a munkahelyén, ez sok vitához vezetett, most viszont eloszlanak a viharfelhők. Egy sikeres ingatlanügy adódik, ragadja meg az alkalmat! A Skorpió-újholddal megreformálhatja pénzügyeit.",
        "Most képes vagy élvezni az élet apró örömeit, a testi szerelmet, szexualitást, a finom dolgokat, szép környezetet. Figyelmed középpontjában az anyagi biztonság megteremtése áll, olyan befektetést, pluszmunkát találhatsz, amivel meg is teremtheted azt. Belső biztonságodat is megtalálod/visszaszerzed, jelentős gyógyulási folyamaton mehetsz át. A Vénusz meglehetősen érzékivé teszi a szerelmi életedet, most nagy örömet találsz a párod közelségében.",
        "„Pénz beszél, kutya ugat” , tartja a mondás. Neked novemberben a legnagyobb kihívás a pénz bevétel-kiadás egyensúlyának megteremtése és megtartása. Biztos lehetsz benne, hogy sok kísértés jön. Csak lemondás árán tudod megoldani, hogy ne menj mínuszba. Különösen nehéz napok: november 5., 8., 9. és 29. De nem kell megijedned, mert lesznek kedvező napok is: 10, 12, 15, 16 és 21. Látod itt is megvan az egyensúly. Sőt a több a kedvező nap, mint a nehéz.",
        "A kétségbeesés fenyeget novemberben. A pénz miatti aggodalom eluralkodhat rajtad. Feladatod a bevétel-kiadás egyensúlyának megteremtése és megtartása. Biztos lehetsz benne, hogy sok kísértés jön. Csak lemondás árán tudod megoldani, hogy ne menj mínuszba. Különösen nehéz napok: 3, 4, 11 és 13. De nem kell megijedned, mert lesznek kedvező napok is: 7 és 17. Látod, kapsz segítséget. Kérdés, hogy észre veszed-e, elfogadod-e, és élsz-e vele…",
        "Megkönnyebbülést jelent számodra, hogy november 4-én a Mars jegyet vált. De sajnálatos módon 3-án szembekerül a Plútóval, és te végképp nem tudod, kire hallgass: a családodra vagy a főnöködre? A magánéletedet vagy a karrieredet építsd? Talán segíthet a Vízöntőbe lépő Plútó november 19-től. De mivel lassú bolygóról beszélünk, nem számíthatsz gyorssegélyre. Biztos, hogy több, sőt, sokkal több időre lesz szükséged, hogy a saját érdeked alapján dönts…"
    ],
    skorpió: [
        "Életedben utoljára történik meg, hogy két uralkodó bolygód, a Mars és a Plútó szembekerül egymással a Rák – Bak tengelyen. Maga a szembenállás november 3-án lesz, de feszítő hatása egész hónapban elkísérhet. Persze csak abban az esetben, ha belemész olyan vitába, amely méltatlan hozzád. Az ellentétek helyett fókuszálj azokra az emberekre és élethelyzetekre, akik és/vagy amik támogatnak, építenek téged. Szép számmal vannak ilyenek. Megtapasztalhatod ezt már november 1-jén, 2-án, 4-én és 19-én is.",
        "Nem szabad félvállról venned mindazt, amire a bolygók figyelmeztetnek. Olyan konstellációk lesznek az égen, amelyek veszélyesek rád nézve és a kapcsolataidra is. Vigyázz magadra és a szeretteidre! A kapcsolataid is törékennyé válhatnak, különösen 3-án, 4-én, 11-én és 13-án. Tegyél meg mindent, hogy ne legyen ok vitára! Megéri kitérni a provokáció elől. Szerencsére lesz két szerencsés nap is: 7-én és 17-én. Mintha a sors kárpótolni akarna…",
        "Ez a november nem olyan lesz, mint a tavalyi, vagy az azelőtti. 8-án lesz egy teljes holdfogyatkozás, ami valójában újhold lenne. Csak a Föld kitakarja a Nap fényét, és a Hold ahelyett, hogy ragyogna, elsötétül. Ez téged fokozott óvatosságra int. Vigyázz az egészségedre és a testi épségedre! Emellett a kapcsolataid is törékennyé válhatnak 5-én, 8-án, 9-én és 29-én. Tegyél meg mindent, hogy ne legyen ok vitára! Megéri kitérni a provokáció elől.",
        "A Skorpió Újhold nagyszerű lehetőséget jelent neked. Itt az ideje, hogy újra meghatározd magad valamilyen személyes módon, például új megjelenéssel vagy az új célok megtalálásával. Ez a hónap mozgalmas időszakot jelez, ugyanis a Mars és a Merkúr lelkesít, amitől energikusnak érzed magad. Gondold át, hogyan mutatod meg magad másoknak, összpontosíts személyes szokásaid megváltoztatására oly módon, hogy növeld önbizalmadat, és koncentrálj arra, hogy a legjobbat nyújtsd, mert ez az az időszak, amikor felfigyelnek rád és erőteljes benyomást keltesz. Persze az a legfontosabb, hogy maradj hű önmagadhoz!",
        "Ez a hónap sok jót tartogat a Skorpiónak! Az egész életét átalakíthatja az Újhold az első sorsterületen, és új ablakot nyithat a világra. A Mars elindul előre, a betervezett munkáival is tud végre haladni, ennek meglesz a haszna anyagilag is, ugyanis a Plútó a Jupiterrel konjunkcióban pénzügyi gyarapodásban részesíti. Valamilyen iratokkal, szerződéssel kapcsolatban késést mutatnak a bolygók, ne ijedjen meg, ez meg nem szünteti, csak késlelteti az ügyet. Párkapcsolata továbbra is szeszélyesnek mondható.",
        "Az első és az ötödik sorsterületét remekül megtámogatják a romantika bolygói, a második életterületen is több planéta kitűnően aspektált, sokkal nagyobb pénzmozgás várható ebben a hónapban, mint amire számított. A hetedik sorsterületén hátráló Uránusz többnyire fényszög nélküli, kicsit kiszámíthatatlannak látszik. Részben lehet ez egy olyan irigység a külvilágból, amivel nem számolt. Esetleg valamelyik régi kedvese szeretné önnel felvenni a kapcsolatot, lehet, hogy most döntéshelyzet elé kerül?",
        "A Mars és a Vénusz kedvezőtlen helyzetben áll. Már akkor is boldognak érezheti majd magát, ha nem értik félre, és elkerülheti a veszekedéseket. Karrierje szempontjából sem ígérnek túl sok jót a bolygók. A Merkúr november 17-étől hátráló mozgásba kezd, és néhány tervét komolyan megzavarhatja. Várjon az új tervekkel, ne siessen el semmit.",
        "A Vénusz az ön jegyében jár – jó esélyei vannak arra, hogy találkozzon azzal, akivel családot alapíthat. Ha nem érzi magát a mennyországban, az azzal van összefüggésben, hogy a Merkúr néhány akadályt gördít az útjába, melyeket először le kell győzni… Ez sikerül is, de energiába kerül, amiből nem rendelkezik túl sokkal. Kímélje magát, aludjon sokat, és éljen egészségesen – akkor minden sikerülni fog!",
        "November a Skorpiók hava! A Nap mellett a Merkúr is a Skorpió jegyében áll, és nem is kap támadást a Skorpió jegye. A hónap első fele igazán a csúcsokat mutatja. Most learathatja az eddigi munkája után járó babérokat, és új dolgokba is belekezdhet. A legjobb időszak arra, hogy közös vállalkozást indítson, ha ezen törné a fejét. Akár még házasságot is köthet!",
        "A Nap a Skorpió jegyében jár már, kellemes fényszögben áll a Neptunusszal. Amikor az ember I. sorsterületén áll a Nap, akkor meg szeretné mutatni magát egy kicsit a világnak, vagy élére akar állni a változásoknak. Tegye hát meg, de ne feledje a többiek tudomására hozni, hogy nélkülük tényleg nem jutna előrébb. Valójában ezt az időszakot legjobb lenne, ha közös munkálkodással töltené másokkal együtt. Barátkozó hangulatban van, s szeretne a központba kerülni, legalább egy kicsit. Elismerésre vágyik családtagjai és barátai részéről. Ne féljen kimutatni, hogy mennyire szüksége van rájuk."
    ],
    nyilas: [
        "A Szaturnusz három éven át „bérli” a Nyilas jegyét. Nagy valószínűséggel külső körülmények kényszerítik arra, hogy fontos tényekkel vagy helyzetekkel szembenézzen, melyeket a múltban talán elhanyagolt vagy magától értetődőnek vett. Ez a fajta élmény az önmegismerés része. A legtöbb embernél, talán Önnél is, ilyenkor válnak tudatossá a saját hibái és az, hogy mi szükséges a jövőbeli fejlődéséhez.",
        "Valójában jó időszakra számíthat. November első heteiben a Vénusz több pénzhez juttatja, és a szerelmi életében is a legjobbakat ígéri. Most igazán mindent beleadhat, remek fordulatok várhatóak a hivatásában és a magánéletében is! A hónap második felében a Merkúr lép a Nyilas jegyébe. A Jupiter is ad Önnek elég energiát. Akár a hivatásában akár a szerelemben a legjobb időszakot élheti meg.",
        "Az otthoni teendők megszaporodhatnak, és talán némileg elvonják a figyelmét az egzisztenciális kérdésekről. Költözködésre, vagy nagy átalakításokra is sor kerülhet a háza táján, amivel sikeresen előkészít egy szerencsés sorsfordulatot. Az anyagiak terén ugyan még várat magára a nagy lehetőség, különösen a más pénzét illető tervei, reményei tűnnek késlekedni.",
        "November 8-án a Jupiter végre belép az ön jegyébe: nagyon szerencsés időszak veszi kezdetét ezzel a nappal. Innentől kezdve akár a karrierjében, akár emberi kapcsolataiban jelentős lépéseket tehet előre. Új ötletek jutnak eszébe, és komoly kapcsolatokat létesíthet, melyből előnyökre tehet szert!",
        "Remek ingatlanvásárlási lehetősége lesz ebben a hónapban, nem biztos, hogy lakóház, inkább vízparti nyaralónak tűnik, nagy valószínűséggel külföldön. Lehet, hogy a szülei is besegítenek a vásárlásba, vagy közösen veszik. Mindenesetre önnek még így is marad a bankszámláján rendesen. Önnek mindig jót tesz a levegőváltozás, ha unatkozna. A pakliban akár egy külföldi álláslehetőség is benne van, de nem olyan, amelyet ön hivatásának tekintene.",
        "Pénzügyei a hónap közepétől maximálisan jól alakulnak, addig egy kicsit aggodalmaskodni fog, mert a Merkúr és a Szaturnusz között kialakult kvadrát késlelteti befektetéseit, vagy a bürokrácia akadályozza a válaszadást hivatalos ügyekben. Szerelmi élete kicsit akadozva halad, mert a Mars az ötödik sorsterületen ugyan előre mozdul, de nem szerelmet hoz, hanem óriási vadászterületet: sok flörtöt mutatnak a bolygók, de bizony kevesen felelnek meg az elvárásainak, igényeinek!",
        "Ez az áttekintés, az elengedés, a lelki, és így a fizikai „akkumulátorok” feltöltésének időszaka. A fókusz most a szolgálat, az empátia általi kiteljesedésen van, de lehet az elvonulás és valamilyen társasági értelemben vett visszavonulás időszaka is, a Mars és a Merkúr szintén teszi a dolgát. Most nagyon könnyen ráhangolódsz mások igényire, és teljes mértékben megnyilvánulnak gyógyító energiáid. Megtalálod érzelmi vagy lelki békéd. A Neptunusz direkt mozgása is ezt a helyzetet segíti elő.",
        "Rosszul viseled a hideget és a sötétet, nem a november a kedvenc hónapod. Igyekezz minden nap találni valamit, aminek örülhetsz! Te nagyon jó vagy abban, hogy apróságok is boldoggá tegyenek. Nem megoldás, ha begubózol, mert lelkileg és testileg is megbetegíted magadat. Legveszélyesebb napok: november 5., 8., 9. és 29. Még szerencse, hogy 16-án Vénusz, 17-én Merkúr, 22-én Nap lép be a Nyilasba, és te teljesen ki leszel cserélve.",
        "Csalódást, változékonyságot, elbizonytalanodást mutatnak a bolygók november 10-én, 23-án, 25-én és 27-én. Fejtörést okozhatnak családi és ingatlan ügyek. A korai sötétedés és hideg, szeles idő sem tesz jót neked. Melegítsd fel magadat forró itallal! Pl. forró teával, forró csokival, forralt borral! És tudd, hogy nincs világvége! Még szerencse, hogy 10-én Merkúr, 22-én Nap, 24-én Mars lép be a Nyilasba, és te ismét tudsz mosolyogni.",
        "November 2-án a Merkúr belép a Nyilasba, s innentől megnehezíti a dolgodat, ha egyetértésre törekszel. Különösen esélytelennek látszik ez 18-án, amikor a Merkúr szembe kerül uralkodó bolygóddal, a Jupiterrel. Ezen a napon, és +/- 1 héten keresztül egyik fél sem érti a másik érveit, emiatt fölösleges belemenned a véleményütköztetés bármely formájába. 21-én a Nap belép a Nyilasba, és innentől jön a te időd: közeleg a születésnapod. Ez remek alkalom, hogy megállj egy pillanatra, és tervezz egy kicsit…"
    ],
    bak: [
        "Visszafordíthatatlan átalakulást jelez a Plútó bolygó, mely végleg kilép a Bakból november 19-én éjjel. Előtte még van lehetőséged azokat a gyökeres változtatásokat véghez vinni, vagy legalább elkezdeni, amelyek a körmödre égnek. De ezt semmiképp se november 3-ra időzítsd, mert a Mars-Plútó szembenállás kíméletlen veszekedést jósol. Szerencsére Vénusz, a Kis szerencse bolygója november 11-én belép a Bakba, és kis szerencsét hoz magával. Ez arra jó, hogy optimistábban lásd a jelent és a jövőt is.",
        "Bolygód, a Szaturnusz november 4-én több mint 4 hónap hátrálás után végre elindul előre. Ettől visszanyered a jövőbe és az életbe vetett hitedet. Emellett ha jót akarsz magadnak, akkor minden beszélgetésbe kapcsolódj be, mert fontos információkhoz juthatsz. Tanulás és/vagy utazás lehetőségét is mutatják a bolygók. Kár lenne kihagynod. Szinte biztos, hogy megbánod, ha nem mész. Nagy kihívás lesz számodra, hogy gyerekes szócsatákból kimaradj 3-án, 4-én, 11-én és 13-án.",
        "Ha jót akarsz magadnak, akkor novemberben minden beszélgetésbe kapcsolódj be, mert fontos információkhoz juthatsz. Emellett tanulás és/vagy utazás lehetőségét is mutatják a bolygók. Kár lenne kihagynod. Szinte biztos, hogy megbánod, ha nem mész. Ezzel párhuzamosan a bevételeid nem úgy alakulnak, ahogy szeretnéd. És nem vigasztal, hogy most mindenkinek nehéz. Kritikus napok: november 7., 10., 11. Ezeken a napokon borúsabban látod a helyzetedet.",
        "A kapcsolódás, kapcsolatteremtés válik hangsúlyossá minden vonalon. Itt az ideje, hogy tisztázd az érzéseid, és megnyugvást találj másokkal való kapcsolataidban. Személyes kötelékeid is megerősödnek. Ha szingli vagy, most rád köszönhet a szerelem, ha kapcsolatban élsz, ismét átélhetitek a régi szenvedélyt. Szakmai téren is a csapatmunka a gyümölcsöző. A Mars és a Merkúr is hangsúlyossá teszi a kapcsolatteremtést, mind társasági, mind szakmai értelemben.",
        "Ebben a hónapban karrierjében sikert-sikerre halmoz, ezt az Újhold segíti elő! Az eddigi szorgalmas munkájának gyümölcsét most aratja le, a Jupiter-Plútó együttállása is erre utal. az első sorsterületen halad a Szaturnusz is, ami ad még némi feladatot, amit a Bak szó nélkül teljesít, annyira szomjazik a sikerre. Szerelmi-téren nem igazán tudja még elhatározni magát: vagy a partner nem alkalmas a tartós kapcsolatra a megítélése szerint, vagy a saját vagyonát tartja kevésnek a családalapításhoz.",
        "A munkahelyén mostanában kissé leterhelte magát, ez gyengélkedéshez vezet, nincs olyan jó állapotban fizikailag, mint szellemileg. A mentális képességei felülmúlhatatlanok, egy nagyobb csoportot érintő találmányával rengeteg összeggel növelheti bankszámláját. Több embert belevon munkájába, de a főszerep az öné. A pénz azonnal áramlik, de pillanatnyilag meg sem közelíti a későbbi eredményeket. A szerelem lehetősége is megnő. Bár ön nem könnyű természet, jót tenne magának is, ha jobban kimutatná az érzelmeit.",
        "Ez a hónap eléggé nehéznek látszik, sok erőt és kitartást követel öntől, de szerencsére ezt megadja a Szaturnusz és a Plútó is a Bak jegyében. A Jupiter jegyet vált, és a Nyilas jegyében folytatja útját. Muszáj lesz saját magát lelkesítenie. Bízzon önmagában, hiszen ön mindent meg tud csinálni! November 15-től a Mars is jegyet vált, átlép a Halak jegyébe, ez pedig erősíteni fogja önt.",
        "Semmi sem akadályozza meg, hogy egyre feljebb és feljebb kerüljön azon a bizonyos szamárlétrán. Az igazság az, hogy a jó sorsfordulathoz most még a nehézségek is hozzásegítik. Vagy azért, mert tanul belőlük, és e tudásából másoknak is juttat, vagy azért, mert éppen ezek inspirálják a további útkeresésre.",
        "Mint mindig, most is a legjobb, ha a hivatását helyezi előtérbe. Nagy lépésekkel tud most előrehaladni, és ezt a felettesei is értékeli fogják. A Merkúr a hónap első felében szenzációs üzleteket ígér, és mire jegyet vált, addigra a Vénusz már a Bak jegyébe lép. Ez nem csak a szerelmi életét javítja, hanem az anyagi ügyeit is. Az egyik legjobb hónapja lesz ez, akár egyedülálló, akár párban él!",
        "Az Ön jegyében áll a Plútó, de kellemetlen kapcsolatban van az Uránusszal. Akár érzékeli a változásokat már az életében, akár nem, a környezete másképp kezd el Önhöz viszonyulni, és ez mindenképp válaszlépésekre, változásokra kényszeríti majd Önt. Ne próbáljon szemet hunyni efelett, különben még kellemetlenebb formában lesz kénytelen szembesülni a tényekkel. Nézzen szembe önmagával és belső változásaival, így erősebb és nemesebb emberként kerülhet ki ebből a tranzitból."
    ],
    vízöntő: [
        "A Mars az Ön 8. sorsterületére került. Ez a tranzit minden bizonnyal valamilyen változást hoz az életébe. Mire vége lesz, személyisége vagy körülményei valahogy átalakulnak, alig észrevehető, vagy éppen drámai módon. Óvakodjon a meggondolatlan és impulzív megnyilvánulásoktól. Másokkal kapcsolatos hosszú távú pénzügyi elképzeléseit ismét mérlegelni kellene. Felül kell vizsgálnia, hogy biztosítási kötvényei megfelelnek-e az aktuális helyzetnek.",
        "A Vénusz a hónap első felében az Ön horoszkópjában a kapott szerelem sorsterülete felett fog átvonulni. Most találkozhat valakivel, aki tökéletesen fog illeni Önhöz. A hónap második felében viszont már a munkájára kellene jobban koncentrálnia. A Merkúr Önnek dolgozik, és számos Önnek előnyös helyzetet teremt majd az üzleti életben. A Mars már a Vízöntő jegyében áll, ettől fáradhatatlannak érzi majd magát.",
        "Munkás napokkal kezdődik ez a hónap, de a munkában a szokottnál is nagyobb szerepet kaphat az utazás, és a kommunikáció. A nyilvános kapcsolataira most jó eséllyel alapozhat, akár akkor ha új munkahelyet keres, akár, ha a meglévő üzletét akarja bővíteni. Egy barátság véget érhet, ha a pénzügyi ellentéteken nem tudnak úrrá lenni. Megint be kell látnia, az üzletet, a pénzügyeket nem jó összekeverni a barátsággal.",
        "Most sok bolygó viszi önt előre, a Merkúr, a Mars, a Vénusz sőt az Uránusz is kedvező helyzetben áll. Tárgyalásai jól sikerülnek. Próbáljon meg együttműködni a kollégáival, mert most feljebb léphet a ranglétrán. A Jupiter november 8-án jegyet vált, a Vénusz a Mérleg jegyében áll, és mindezen bolygóállások sok erőt, és nagyon jó ötleteket adnak önnek. A mennyekben érezheti majd magát, igazán nem lesz hiány a boldogságból. Akár még házasságot is köthet!",
        "Valószínűleg megválik munkahelyétől, úgy érzi, nem értékelik eléggé kreativitását, önnek egy kötetlen, szabadúszói állás felelne meg, vagy ha mégis egy vállalatnál dolgozna, akkor egy csoportnak az irányítása tenné boldoggá, ahol teljesen szabad kezet kap. Nem biztos, hogy ez az új munkahely lesz a végleges...",
        "A Vízöntő szeret egyedül lenni, több okból is, korszakalkotó gondolatai ekkor szoktak kipattanni a fejéből, és ilyenkor a lelke is megnyugszik. Egyébként is, mint amolyan tudós fajta, szeret elvonulni. Most is ilyen időszakot élhet meg, valamin nagyon fáradozik, melyet hamarosan a világ elé tár. Rövidesen új korszak kezdődik az életében, ehhez köze lehet egy költözésnek is. Az ingatlankérdések már régóta foglalkoztatják.",
        "Az Újhold kiemeltté teszi a társadalomban betöltött pozíciódat. Nagy előrelépést tehetsz a munkádban, és új célokat fogalmazhatsz meg minden fronton. Valamiképpen az is megújul, ahogyan önmagadat definiálod, és nagyobb fegyelmezettségre teszel szert. Most kitartóan tudsz küzdeni az álmaidért. A karrierkérdések állnak a figyelmed középpontjában, szeretnél előbbre jutni az életedben, és sikerrel jársz a célkitűzéseidben, mert most nagyon is reálisan gondolkodsz.",
        "Két tűz között érezheted magad szinte egész novemberben. Hol a főnököd, hol a családod elégedetlenkedik. Mindketten keveslik azt, amit nyújtasz. Lehet, hogy azért, mert szeretnél kicsit egyedül lenni saját magaddal. Szét kell szakadnod, hogy párhuzamosan több helyen teljesíteni tudj? Legnehezebb kihívások ezeken a napokon várnak rád: november 7-én, 10-én, 11-én. Szerencsére lesz egy nagyszerű nap: november 28.",
        "Feszült leszel novemberben. Hol a főnököd, hol a családod elégedetlenkedik. Mindenki többet akar tőled. Holott te csak szeretnél kicsit egyedül lenni saját magaddal. Szét kell szakadnod, hogy párhuzamosan több helyen teljesíteni tudj. Legnehezebb kihívások ezeken a napokon várnak rád: november 3-án, 4-én, 11-én és 13-án. Szerencsére enyhül a nyomás azáltal, hogy bolygók sorban jegyet váltanak: 10-én Merkúr, 22-én Nap, 24-én Mars.",
        "Trambulin ugrással ér fel az, hogy a Plútó november 19-én éjjel belép a Vízöntőbe. Tavaly március 23-án tette ezt meg először, majd visszafordult a Bakba és kilépés után újból idén január 21-én ismét belépett a Vízöntőbe. A bátorság még év elején nem volt kellően eltökélt, ezért adott további időt neked. November 19-től viszont egyértelműen azt mondja, nincs több esélyed a könnyebb ellenállás felé menni. Örülj neki! Lerázhatsz magadról minden elavult, visszahúzó tévhitet, kapcsolatot, körülményt. Erre készülsz hónapok óta, nem igaz?"
    ],
    halak: [
        "A Halakban járó Szaturnusz június 29. óta tartó hátrálását befejezve november 15-én végre ismét elindul előre. Előtte három nappal stacioner, vagyis „áll”. Természetesen egyetlen bolygó sem áll egyhelyben. Ám értelmezése szerint megállhatsz egy kicsit, körbe nézhetsz, hogy ide akartál-e jutni, és eldöntheted, merre akarsz tovább haladni. Szaturnusz, Kronosz, az Idő ura azt javasolja, ne húzd tovább az időt. Csak akkor segít neked, ha valamerre lépsz…",
        "November 4-én befejezi a hátrálást a Halakban járó Szaturnusz, és elindul előre. Az eddig lassító energiák megszűnnek. Vége a nosztalgiázásnak. Innentől arccal előre! Szuper napjaid lesznek: november 7, 17. Időzítsd ide a fontosabb ügyeidet! Sajnos vitát és súlyos nézeteltérést mutatnak a bolygók 3-án, 4-én, 11-én és 13-án. A felek minden esetben harciasan védik a saját érdekeiket. Ne hagyd magad, de ügyelj a stílusodra és a szavaidra!",
        "November 24-én befejezi a hátrálást a Halakban járó Jupiter, és elindul előre. Addig viszont még lassító energiákat érzékelhetsz. Meglepő módon most egész jól viseled. Tágra nyílt szemekkel figyelj, hogy mi az, ami régen nem, de most összejöhet. A sors szeretne kárpótolni. És meglehetősen fortélyos, leleményes módon fogja ezt megtenni. Szuper napjaid lesznek: november 10., 12., 15., 16. és 21. Időzítsd ide a fontosabb ügyeidet!",
        "Spirituálisan még nyitottabbá válsz a következő időszakban, keresed a mélyebb válaszokat, összefüggéseket. Olyan élményekben lehet részed, amelyek megadják ezt neked, és valóban értékes felismeréseid lehetnek. Ennek mentén újrafogalmazhatod vágyaidat, álmaidat, most komoly számvetésen mész keresztül, aminek sikerül pozitív perspektívákat adni. Felemlő megéléseid lehetnek.",
        "Pénzügyei ebben a hónapban megoldódnak, vagy plusz havi fizetést kap, vagy nem kell többé támogatnia valakit. Új barátai, ismerősei jó hatással vannak a Halakra, a társasági programok, összejövetelek jót tesznek a lelkének. Szerencsés helyzetben van, mert ami nyomasztja, abban segítséget kap. A Jupiter-Plútó konjukciója belső fejlődést jelez, amelyet rövidesen a külső változások is követik.",
        "Ön igazi csapatjátékos, pillanatok alatt felveszi az éppen aktuális hangulatot és együtt húz a többiekkel, ha arra van szükség. A munkahelyén remekül teljesít, elégedettek önnel, ennek fizetéskor a jelét is adják. Ön nem igazán takarékos fajta, de a pénz önt megtalálja. Biztosítást köt, vagy állampapírokba helyezi a pénzét, amely nagyon jól jövedelmez. Ebben a hónapban ön igazán erős, ha kell, meg tudja védeni magát.",
        "A Jupiter november 8-án jegyet vált, és ez nem tesz jót önnek. A Merkúr is kedvezőtlen helyzetben van, a Mars pedig csak november 16-án lép a Halak jegyébe. Úgy érezheti, mintha egy kicsit a feje tetejére állna a világ ön körül. Egyre zavaróbbnak találja például az önhöz közel állók viselkedését. Nagy szüksége lenne egy kis csendes elvonulásra! Komoly nehézségei adódhatnak, és ezeket csak akkor tudja leküzdeni, ha képes kompromisszumot kötni, és együttműködni másokkal.",
        "Az otthoni átalakítások megint előtérbe kerültek az életében. Lehetősége van, hogy szebbé és kényelmesebbé tegye a családi fészket. Meglehet, ez rengeteg pénzét felemészti, de nem bánja meg, ha látja majd a végeredményt. Az üzleti életében is módja van a fejlesztésre. A külföldi lehetőségeket is érdemes számba vennie.",
        "A hónap első felében három bolygó is támadja a Halak jegyét, ezért készüljön fel kisebb-nagyobb nehézségeke. Nagyon vigyázzon a pénzére, ha teheti, ne hordjon magánál készpénzt. Csak úgy menjen el vásárolni, hogy ír egy listát, és szigorúan tartja magát hozzá. A hónap első felében többnyire egyedül lesz. A hónap második felében a Vénusz jó fényszöget vet a Halak jegyére, és Ön ismét fürödhet az elismerő pillantásokban, a szerelemben!",
        "Az Ön uralkodó bolygója, a Neptunusz kellemetlen kapcsolatba került a Szaturnusszal. Szervezzen le a háziorvosával egy alapos egészségügyi vizsgálatot, mert ez a bolygókapcsolat néha egy egészségügyi probléma kezdetét jelzi. Kétségei támadhatnak, és bizonytalanul érezheti magát, talán még az is eszébe jut, hogy mindent felad és visszavonul a világtól, mint egy remete. Félelmek is gyötörhetik, minden különösebb ok nélkül. Gondoljon arra, hogy mindez csak átmeneti jelenség. Keresse az életvidám, lendületes barátok társaságát, ők jelentik az igazi és szükséges segítséget, az ember csak felfelé nézhet, ha gödörben érzi magát."
    ]
    
};

// horoszkóp generálása
function generateHoroscope() {
    // lekérés
    const sign = document.getElementById("horoscope").value;
    
    // random pick
    const horoscopesForSign = horoscopes[sign];
    const randomHoroscope = horoscopesForSign[Math.floor(Math.random() * horoscopesForSign.length)];
    
    // print
    document.getElementById("result").innerText = randomHoroscope;
}
